version: '3'

services: 
  app: 
    build:
      context: ./timecard-system
      dockerfile: Dockerfile
    container_name: TimeCard-system
    environment: 
      - NODE_ENV=development
    volumes: 
      - ./:/usr/src/timecard-system
    command: /bin/sh
    ports: 
      - '3000:3000'
    tty: true

  backend:
    build:
      context: ./go-admin
      dockerfile: Dockerfile
    ports:
      # ローカル:Docker
      - 8000:3000
      # DockerとローカルのFSをマウント
    volumes:
      - ./go-admin:/app
    depends_on:
      - db
  db:   
    image: mysql:8.0
    platform: linux/x86_64
    # restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    # ローカルに.dbdataを作成し、dbコンテナとFSをマウントする
    volumes:
      - ./go-admin/.dbdata:/var/lib/mysql
    ports:
      - 33066:3306